package com.example.electronicelectionapp.theRemote.dataClass.addNewElection

data class Voters(

    val english: String,
    val Y1: String,
    val Y1G1: String,
    val Y1G2: String,
    val Y1G3: String,
    val Y1G4: String,
    val Y1G5: String,
    val Y1G6: String

    //    val BIS: CheckBox,
//    val Y2BIS: CheckBox,
//    val Y2G1BIS: CheckBox,
//    val Y2G2BIS: CheckBox,
//    val Y2G3BIS: CheckBox,
//    val Y3BIS: CheckBox,
//    val Y3G1BIS: CheckBox,
//    val Y3G2BIS: CheckBox,
//    val Y3G3BIS: CheckBox,
//    val Y4BIS: CheckBox,
//    val Y4G1BIS: CheckBox,
//    val Y4G2BIS: CheckBox,
//    val Y4G3BIS: CheckBox,
//    val IBM: CheckBox,
//    val Y2IBM: CheckBox,
//    val Y2G1IBM: CheckBox,
//    val Y2G2IBM: CheckBox,
//    val Y2G3IBM: CheckBox,
//    val Y3IBM: CheckBox,
//    val Y3G1IBM: CheckBox,
//    val Y3G2IBM: CheckBox,
//    val Y3G3IBM: CheckBox,
//    val Y4IBM: CheckBox,
//    val Y4G1IBM: CheckBox,
//    val Y4G2IBM: CheckBox,
//    val Y4G3IBM: CheckBox,
//    val arabic: CheckBox,
//    val banks: CheckBox,
//    val Y2Banks: CheckBox,
//    val Y2G1Banks: CheckBox,
//    val Y2G2Banks: CheckBox,
//    val Y2G3Banks: CheckBox,
//    val Y3Banks: CheckBox,
//    val Y3G1Banks: CheckBox,
//    val Y3G2Banks: CheckBox,
//    val Y3G3Banks: CheckBox,
//    val Y4Banks: CheckBox,
//    val Y4G1Banks: CheckBox,
//    val Y4G2Banks: CheckBox,
//    val Y4G3Banks: CheckBox,
//    val HR: CheckBox,
//    val Y2HR: CheckBox,
//    val Y2G1HR: CheckBox,
//    val Y2G2HR: CheckBox,
//    val Y2G3HR: CheckBox,
//    val Y3HR: CheckBox,
//    val Y3G1HR: CheckBox,
//    val Y3G2HR: CheckBox,
//    val Y3G3HR: CheckBox,
//    val Y4HR: CheckBox,
//    val Y4G1HR: CheckBox,
//    val Y4G2HR: CheckBox,
//    val Y4G3HR: CheckBox,
//    val IS: CheckBox,
//    val Y2IS: CheckBox,
//    val Y2G1IS: CheckBox,
//    val Y2G2IS: CheckBox,
//    val Y2G3IS: CheckBox,
//    val Y3IS: CheckBox,
//    val Y3G1IS: CheckBox,
//    val Y3G2IS: CheckBox,
//    val Y3G3IS: CheckBox,
//    val Y4IS: CheckBox,
//    val Y4G1IS: CheckBox,
//    val Y4G2IS: CheckBox,
//    val Y4G3IS: CheckBox,
//    val MPF: CheckBox,
//    val Y2MPF: CheckBox,
//    val Y2G1MPF: CheckBox,
//    val Y2G2MPF: CheckBox,
//    val Y2G3MPF: CheckBox,
//    val Y3MPF: CheckBox,
//    val Y3G1MPF: CheckBox,
//    val Y3G2MPF: CheckBox,
//    val Y3G3MPF: CheckBox,
//    val Y4MPF: CheckBox,
//    val Y4G1MPF: CheckBox,
//    val Y4G2MPF: CheckBox,
//    val Y4G3MPF: CheckBox

)